// <auto-generated />
using System;
using EFGetStarted.AspNetCore.NewDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.AspNetCore.NewDb.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20181021112200_addedOptimalPlanTable")]
    partial class addedOptimalPlanTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.ClassesWeNeed.OptimalPlan", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.Property<string>("Cuisine");

                    b.Property<DateTime?>("Date");

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("Price");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("OptimalPlans");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.ClassesWeNeed.RestaurantInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cuisine");

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.HasKey("Id");

                    b.ToTable("RestaurantInfo");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.ClassesWeNeed.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.ClassesWeNeed.UserPlans", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("allDates");

                    b.Property<string>("city");

                    b.Property<string>("cuisines");

                    b.Property<string>("endTime");

                    b.Property<string>("planName");

                    b.Property<string>("price");

                    b.Property<string>("startTime");

                    b.HasKey("Id");

                    b.ToTable("UserPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
